name: advent-calendar
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  run_command: gunicorn --chdir website app:app
  environment_slug: python
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
static_sites: []
